application/views/user.py
from sqlalchemy import desc

from flask import Blueprint, render_template, jsonify, url_for, flash, redirect, request as flask_request
from flask_login import LoginManager, current_user, login_user, logout_user, login_required

from application import app
from application.models import *
from application.utils import utils

user = Blueprint('user', __name__)


@user.route('/user/login', methods = ['POST', 'GET'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('index'))

	next_url = flask_request.args.get('next', flask_request.form.get('next', ''))
     
	if flask_request.method == 'POST':
		email = flask_request.form['email']
		user = UserModel.query.filter_by(email = email).first()
		if user is not None and user.check_password(flask_request.form['password']):
			if (not user.role):
				flash('Your account is disabled', 'error')
			else:
				utils.set_last_login(user.id)
				login_user(user)
				flash('You are now logged in')
				if (next_url):
					return redirect(next_url)
				else:
					return redirect(url_for('index'))
		else:
			flash('Wrong email address or password', 'error')
     
	return render_template('user/login.html',
		title='Login',
		menu='login',
		next=next_url)

@user.route('/user/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
     
    if flask_request.method == 'POST':
        email = flask_request.form['email']
        username = flask_request.form['name']
        password = flask_request.form['password']
 
        if UserModel.query.filter_by(email=email).first():
            return ('Email already Present')
	
		# -TODO- register with role = 0 and send confirmation email to move to 1
        user = UserModel(email=email, name=username, role=1)
        user.set_password(password)
        user.check_gravatar(True)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.login'))

    return render_template('user/register.html',
		title='Register',
		menu='register')

@user.route('/logout')
def logout():
	logout_user()
	flash('You are now logged out')
	return redirect(url_for('index'))

application/templates/user/login.html
{% extends "/layout/page.html" %}

{% block content %}

<form action="{{ request.path }}" method="POST" class="p-5" style="max-width:400px; margin: 0 auto">

    <input type="hidden" name="next" value="{{ next }}" />

    <div class="mb-3 row">
        <label for="name" class="col-sm-3 col-form-label">Email</label>
        <div class="col-sm-9">
            <input type="email" name="email" class="form-control" value="" />
        </div>
    </div>

    <div class="mb-3 row">
        <label for="name" class="col-sm-3 col-form-label">Password</label>
        <div class="col-sm-9">
            <input type="password" name="password" class="form-control" value="" />
        </div>
    </div>

    <div class="mb-3 row">
        <div class="offset-sm-3 col-sm-9">
            <input type="submit" value="Login" class="btn btn-primary" />
            <a href="{{ url_for('user.register') }}" class="btn btn-link">Register</a>
        </div>
    </div>

</form>

{% endblock %}

application/templates/user/register.html
{% extends "/layout/page.html" %}

{% block content %}

<div class="p-5" style="max-width:600px; margin: 0 auto">
    <h4>Already Have an Account?</h4>
    <p><a href ="{{url_for('user.login')}}">Login Here</a></p>

    <hr />

    <h4>Create a new account</h4>
    <form action="{{ request.path }}" method = "POST">

        <div class="mb-3 row">
            <label for="name" class="col-sm-3 col-form-label">Name</label>
            <div class="col-sm-9">
                <input type="text" name="name" class="form-control" value="" />
            </div>
        </div>

        <div class="mb-3 row">
            <label for="name" class="col-sm-3 col-form-label">Email</label>
            <div class="col-sm-9">
                <input type="email" name="email" class="form-control" value="" />
            </div>
        </div>

        <div class="mb-3 row">
            <label for="name" class="col-sm-3 col-form-label">Password</label>
            <div class="col-sm-9">
                <input type="password" name="password" class="form-control" value="" />
            </div>
        </div>

        <div class="mb-3 row">
            <div class="offset-sm-3 col-sm-9">
                <input type="submit" value="Register" class="btn btn-primary" />
            </div>
        </div>

    </form>
</div>

{% endblock %}