application/views/projects.py
from sqlalchemy import desc

from flask import Blueprint, render_template, jsonify, redirect, request, url_for, flash, g
from flask_login import login_required, current_user

from application import app
from application.models import *
from application.utils import utils

projects = Blueprint('projects', __name__)

@projects.before_request
@login_required
def login_required_for_all_request():    
    pass  

@projects.route("/projects")
def project_list():
    # List of projects, invitations, join and leave projects
    projects = utils.load_projects(current_user)
    # list archived projects
    pqry = ProjectModel.query
    if current_user.role < 4:
        pqry = pqry.join(ProjectUserModel) \
            .filter(ProjectModel.status == 0, ProjectUserModel.user_id == current_user.id)
    else:
        pqry = pqry.filter(ProjectModel.status == 0)
    archlist = utils.parse_projects(pqry.order_by(ProjectModel.title).all(), current_user.id)
    # list users
    users = UserModel.query.filter(UserModel.role > 0).order_by(UserModel.name).all()
    # prepare view
    g.jscript.append(url_for('static', filename='js/dragula.min.js'))
    g.jscript.append(url_for('static', filename='js/projects.js'))
    return render_template("projects.html",
        title="Pacific Data Hub",
        projects=projects,
        archived=archlist,
        users=users,
        menu="projects_list"
    )

@projects.route("/projects/<int:id>")
def project_view(id):
    project = ProjectModel.query.filter_by(id=id).first()
    if not project:
        flash('Project not found', 'error')
        return redirect(url_for('projects.project_list'))
    asso = ProjectUserModel.query.filter_by(project_id=id, user_id=current_user.id).first()
    if not asso:
        flash('Access denied', 'error')
        return redirect(url_for('projects.project_list'))
    # list users
    users = UserModel.query.filter(UserModel.role > 0).order_by(UserModel.name).all()
    # prepare view
    g.jscript.append(url_for('static', filename='js/projects.js'))
    return render_template("projects_view.html",
        title="Pacific Data Hub",
        data = utils.parse_project(project, current_user.id),
        project = project.get_html(),
        status = project.status,
        users=users,
        menu="projects_list"
    )

@projects.route("/api/project/load/<id>")
@projects.route("/api/project/load/<id>/<mode>")
def api_project_load(id, mode="data"):
    if current_user.role < 1:
        return jsonify({'error': 'Action not allowed'})
    item = ProjectModel.query.filter_by(id=id).first()
    if not item:
        return jsonify({'error': 'Project does not exist'})
    if mode == 'data':
        return jsonify(item.get_dict())
    else:
        return jsonify(item.get_html())


@projects.route("/api/project/save", methods=['POST'])
def api_project_save():
    pid = int(request.form['id']) if request.form.get('id') else False
    # init project
    item = ProjectModel()
    if pid:
        item = ProjectModel.query.filter_by(id=pid).first()
        if not item:
            return jsonify({'error': 'Project does not exist'})
        err = utils.wrong_project_permission(pid, current_user.id, 2)
        if err:
            return jsonify(err)
    # set properties
    item.title = request.form.get('title','').strip()
    item.description = request.form.get('description','')
    item.setDate('start',request.form.get('start') or None)
    item.setDate('deadline', request.form.get('deadline') or None)
    item.budget = request.form.get('budget') or None # TODO check float
    item.status = request.form.get('status', 0)
    # check
    is_valid = item.is_valid()
    if is_valid != True:
        return jsonify({'error': list(is_valid.values())})
    # add default user to new projects
    if not pid:
        asso = ProjectUserModel()
        asso.member = current_user
        asso.project = item
        asso.role = 2 # admin
        db.session.add(asso)
    # save in DB
    db.session.commit()
    # report to user
    msg = "Project {}".format('Updated' if pid else 'Created')
    flash(msg, 'success')
    return jsonify({
        'success': msg,
        'pid': item.id
    })

@projects.route("/api/project/lists/save", methods=['POST'])
def api_project_lists_save():
    pid = request.form.get('pid')
    err = utils.wrong_project_permission(pid, current_user.id, 1)
    if err:
        return jsonify(err)
    # Load projct
    proj = ProjectModel.query.get(pid)
    # Create list item
    if (request.form.get('newitem')):
        item = ListModel(
            project_id = pid,
            title=request.form['newitem'],
            position = proj.get_next_list_position(),
            status = 1
        )
        db.session.add(item)
        db.session.commit()
        return jsonify({
            'success': "New list created",
            'pid': pid,
            'lid': item.id,
            'position': item.position
        })
    else:
        # save list items
        items = request.form.to_dict()
        pos = 0
        for idx in items:
            if 'item_' in idx:
                lid = int(idx[5:])
                item = ListModel.query.get(lid)
                if items[idx]:
                    # -TODO- delete lists with empty names?
                    item.title = items[idx]
                item.project_id = pid
                item.position = pos
                pos = pos+1
        db.session.commit()
        msg = 'List item saved!'
        return jsonify({
            'success': msg,
            'noreload': True,
            'pid': pid
        })

@projects.route("/api/project/lists/del/<int:id>", methods=['GET','POST'])
def api_project_lists_del(id):
    # 1. load list
    item = ListModel.query.get(id)
    # 2. Check admin rights
    err = utils.wrong_project_permission(item.project_id, current_user.id, 2)
    if err:
        return jsonify(err)
    # 3. load tasks and check list is empty
    # -TODO-
    # 4. delete list
    db.session.delete(item)
    db.session.commit()
    # 5. frontend feedback
    if request.form.get('frontend', False):
        flash('List deleted!')
    return jsonify({
        'success': 'List deleted!'
    })

@projects.route("/api/project/members/save", methods=['POST'])
def api_project_members_save():
    pid = request.form.get('pid')
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    # load current members
    assos = ProjectUserModel.query.filter_by(project_id=pid).all()
    members = []
    for itm in assos:
        members.append(itm.user_id)
    # add new members
    tot = 0
    for mid in request.form.get('usersel'):
        if mid not in members:
            asso = ProjectUserModel()
            asso.user_id = mid
            asso.project_id = pid
            asso.role = 0 # guest
            db.session.add(asso)
            tot = tot+1
    if tot:
        db.session.commit()
    # report
    msg = f"{tot} members added to project"
    flash(msg, 'success')
    return jsonify({
        'success': msg,
        'pid': pid
    })

@projects.route("/api/project/members/promote/<int:pid>/<int:uid>", methods=['GET','POST'])
def api_project_members_promote(pid, uid):
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    asso = ProjectUserModel.query.filter_by(project_id=pid, user_id=uid).first()
    if asso.role < 2:
        asso.role = asso.role + 1
        db.session.commit()
        msg = "User successfully promoted"
        flash(msg, 'success')
        return jsonify({
            'success': msg,
            'pid': pid
        })
    else:
        return jsonify({
            'error': 'Member is already an admin'
        })

@projects.route("/api/project/members/demote/<int:pid>/<int:uid>", methods=['GET','POST'])
def api_project_members_demote(pid, uid):
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    asso = ProjectUserModel.query.filter_by(project_id=pid, user_id=uid).first()
    if asso.role > 0:
        asso.role = asso.role - 1
        db.session.commit()
        msg = "Member successfully demoted"
        flash(msg, 'success')
        return jsonify({
            'success': msg,
            'pid': pid
        })
    else:
        return jsonify({
            'error': 'Member is already a guest'
        })

@projects.route("/api/project/members/remove/<int:pid>/<int:uid>", methods=['GET','POST'])
def api_project_members_remove(pid, uid):
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    asso = ProjectUserModel.query.filter_by(project_id=pid, user_id=uid).first()
    db.session.delete(asso)
    db.session.commit()
    # report
    msg = "User successfully removed from project members"
    flash(msg, 'success')
    return jsonify({
        'success': msg,
        'pid': pid
    })
    
@projects.route("/api/project/archive/<int:pid>", methods=['GET','POST'])
def api_project_archive(pid):
    # Load project and check permissions
    item = ProjectModel.query.filter_by(id=pid).first()
    if not item:
        return jsonify({'error': 'Project does not exist'})
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    # update status (0 = closed)
    item.status = 0
    # save in DB
    db.session.commit()
    # report
    msg = "Project has been archived"
    flash(msg, 'success')
    return jsonify({
        'success': msg,
        'pid': pid
    })

@projects.route("/api/project/open/<int:pid>", methods=['GET','POST'])
def api_project_open(pid):
    # Load project and check permissions
    item = ProjectModel.query.filter_by(id=pid).first()
    if not item:
        return jsonify({'error': 'Project does not exist'})
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)

application/views/settings.py
from sqlalchemy import desc

from flask import Blueprint, render_template, jsonify, request, url_for, flash, g
from flask_login import login_required, current_user

from application import app
from application.models import *
from application.utils import utils

settings = Blueprint('settings', __name__)

@settings.before_request
@login_required
def login_required_for_all_request():    
    pass

@settings.route("/settings/account")
def account():
	# User account settings, i.e. name, email, password, avatar
	# item = UserModel.query.get(current_uset)
	g.jscript.append(url_for('static', filename='js/settings_account.js'))
	return render_template("settings_account.html",
		title="Pacific Data Hub",
		menu="settings_account",
		data=current_user,
		timezones=utils.get_timezones()
	)

@settings.route("/settings/preferences")
def preferences():
	# User preferences, i.e. timezone, default view, notifications, outlook sync
	opts = {
		'default_views': app.config['TASK_VIEWS']
	}
	g.jscript.append(url_for('static', filename='js/settings_preferences.js'))
	return render_template("settings_preferences.html",
		title="Pacific Data Hub",
		menu="settings_preferences",
		data=current_user.get_preferences(),
		options = opts
	)

@settings.route("/api/preferences/save", methods=['POST'])
def api_preferences_save():
	uid = int(request.form['id']) if request.form.get('id') else current_user.id
	if uid != current_user.id and current_user.role < 3:
		return jsonify({'error': 'You must be admin to edit users'})
	item = UserModel.query.filter_by(id=uid).first()
	if not item:
		return jsonify({'error': 'User does not exist'})
	item.set_preference('default_view', request.form.get('default_view', 'list'))
	item.set_preference('notif_instant', request.form.get('notif_instant', False))
	item.set_preference('notif_daily', request.form.get('notif_daily', False))
	db.session.commit()
	msg = "User preferences saved"
	return jsonify({'success': msg})

@settings.route("/settings/users")
def users():
	# User management
	qry = UserModel.query
	if (current_user.role < 4):
		qry = qry.filter(UserModel.role > 0)
	items = qry.order_by(desc(UserModel.role), UserModel.name).all()
	g.jscript.append(url_for('static', filename='js/settings_users.js'))
	return render_template("settings_users.html",
		title="Pacific Data Hub",
		menu="settings_users",
		data=items,
		roles=app.config['USER_ROLES'],
		timezones=utils.get_timezones()
	)

@settings.route("/api/users/load/<id>")
def api_user_load(id):
	if current_user.role < 2:
		return jsonify({'error': 'Action not allowed'})
	item = UserModel.query.filter_by(id=id).first()
	if not item:
		return jsonify({'error': 'User does not exist'}) 
	if current_user.role <= item.role:
		return jsonify({'error': 'Action not allowed'})
	if not item.timezone:
		item.timezone = 'UTC'
	return jsonify(item.get_dict())

@settings.route("/api/users/save", methods=['POST'])
def api_user_save():
	uid = int(request.form['id']) if request.form.get('id') else False
	uro = int(request.form['role']) if request.form.get('role') else 0
	if (uid != current_user.id and uro > current_user.role):
		# trying to raise user to a higher level than ourself
		return jsonify({'error': 'Action not allowed'})
	# set user
	item = UserModel()
	if uid:
		item = UserModel.query.filter_by(id=uid).first()
		if not item:
			return jsonify({'error': 'User does not exist'})
		elif uid != current_user.id:
			if current_user.role < 3:
				return jsonify({'error': 'You must be admin to edit users'})
			if current_user.role <= item.role:
				return jsonify({'error': 'Can not edit user with a higher role'})
	elif current_user.role < 3:
		return jsonify({'error': 'You must be admin to create users'})
		
	item.name = request.form.get('name','').strip()
	item.timezone = request.form.get('timezone','UTC')
	if not uid or (uid != current_user.id and current_user.role > 3):
		# set email only for new users
		# only super admin can change email (for now)
		item.email = request.form.get('email','').strip()
	if (uid and uid == current_user.id):
		# user is updating itself
		item.thumbnail = request.form.get('thumbnail', '')
	else:
		# admin is updating another user
		item.role = uro
	# check if password is getting updated
	pwd = request.form.get('password','').strip()
	if (pwd):
		# set password only when creating or updating it
		# -TODO- check if the password is secure enough (within set_password method)
		item.set_password(pwd)
	if not item.is_valid():
		return jsonify({'error': 'Missing or invalid fields'})
	if not uid:
		db.session.add(item)
	db.session.commit()
	msg = "User {}".format('Updated' if uid else 'Created')
	flash(msg, 'success')
	return jsonify({
		'success': msg, 
		'avatar': item.avatar()
	})


@settings.route("/api/users/delete/<int:id>", methods=['POST'])
def api_user_delete(id):
	# id = int(request.form['id']) if request.form.get('id') else False
	if not id:
		return jsonify({'error': 'User not specified'})
	if current_user.role < 3:
		return jsonify({'error': 'Insufficient permissions #2'})
	item = UserModel.query.get(id)
	if item:
		# delete if no task, no comment, nothing
		# db.session.delete(item)
		# else disable it
		item.role = 0
		db.session.commit()
		flash('User account has been disabled', 'success')
		return jsonify({'success': 'User disabled'})
	else: 
		return jsonify({'error': 'User does not exist'})
    # return redirect(url_for('adminUser'))

application/templates/projects.html
{% extends "layout/projects.html" %}

{% block content %}
<h2 class="page-title">
  {% if current_user.role > 0 %}
  <button type="button" class="btn btn-outline-primary btn-sm float-end" data-bs-toggle="modal"
    data-bs-target="#editModal"><i class="bi bi-plus-lg"></i></button>
  {% endif %}
  Projects
</h2>
<div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-cols-xxl-4 g-4 mb-4">
  {% for project in projects %}
  <div class="col">
    <{% if project.isadmin %}form action="{{ url_for('projects.api_project_lists_save') }}" method="post"{% else %}div{% endif %} data-id="{{ project.id }}" class="card card-project{% if project.isadmin %} project-admin{% endif %}">
      <div class="card-header {{ project.class }}">
        {% if project.isadmin %}
        <input type="hidden" name="pid" value="{{ project.id }}" />
        <a href="#!" class="btn btn-action btn-project-edit pt-2 pe-0 float-end" data-id="{{ project.id }}"><i class="bi bi-pencil-fill"></i></a>
        {% endif %}
        <h5 class="card-title pt-1"><a href="{{ url_for('projects.project_view', id=project.id ) }}" class="btn-project-info pt-1">{{ project.title }}</a></h5>
      </div>
      <div class="card-body pb-2">
        {% if project.start or project.deadline or project.budget %}
        <div class="project-more text-muted pb-3">
          {{ project.start or '<i class="bi bi-three-dots text-muted"></i>' | safe }}
          <i class="bi bi-caret-right-fill opacity-75"></i>
          {{ project.deadline or '<i class="bi bi-three-dots text-muted"></i>' | safe }}
          {% if project.budget %}
          <div class="float-end"><i class="bi bi-piggy-bank pe-1"></i>{{ project.budget | format_number }}</div>
          {% endif %}
        </div>
        {% endif %}
        <h5>Lists</h5>
        <ul class="project-lists{% if project.isadmin %} project-dragula{% endif %}">
          {% for list in project.lists %}
          <li class="project-lists-item">
            {% if project.isadmin %}
            <i class="bi bi-grip-vertical gu-handle py-2 pe-1"></i>
            <input name="item_{{ list.id }}" type="text" class="form-control form-control-plaintext" value="{{ list.title }}" />
            <button type="button" data-lid="{{ list.id }}" class="btn btn-action btn-list-delete"><i class="bi bi-trash"></i></button>
            <!-- -TODO- disable button if list has tasks -->
            {% else %}
            <span class="py-2 flex-grow-1">{{ list.title }}</span>
            {% endif %}
          </li>
          {% endfor %}
        </ul>
        {% if project.isadmin %}
        <div class="d-flex mb-3" style="margin-top:-.75em">
          <input name="newitem" type="text" class="form-control border-0" value="" placeholder="Create new list" />
          <button type="submit" class="btn btn-action"><i class="bi bi-plus-circle"></i></button>
        </div>
        {% endif %}
        <h5 class="py-1 my-2 border-bottom">Members</h5>
        <div class="project-users">
        {% for ridx, rlabel in [('r2','admin'),('r1','member'),('r0','observer')] %}
          {% for member in project.get(ridx) %}
          <div data-userid="{{ member.id }}" class="btn-user btn-user-{{ rlabel }} dropdown-center order-2 order-md-5">
            {% set rn = ridx[1] | int %}
            <a href="#!" class="dropdown-toggle arrow-none text-muted" data-bs-toggle="dropdown" aria-expanded="false">{{ member.avatar(rlabel | title) | safe }}</a>
            <ul class="dropdown-menu">
              <li><h6 class="dropdown-header">{{ member.name }} ({{ rlabel | title}})</h6></li>
              <li><a href="javascript:void(0);" class="dropdown-item"><i class="bi bi-person-square me-2"></i>View profile</a></li>
              {% if project.isadmin and member.id != current_user.id %}
              {% if rn < 2 %}
              <li><a href="{{ url_for('projects.api_project_members_promote', pid=project.id, uid=member.id) }}" data-tfk-ajax="post" class="dropdown-item"><i class="bi bi-caret-up-square text-success me-2"></i>Promote member</a></li>
              {% endif %}
              {% if rn > 0 %}
              <li><a href="{{ url_for('projects.api_project_members_demote', pid=project.id, uid=member.id) }}" data-tfk-ajax="post" class="dropdown-item"><i class="bi bi-caret-down-square text-warning me-2"></i>Demote member</a></li>
              {% endif %}
              <li><a href="{{ url_for('projects.api_project_members_remove', pid=project.id, uid=member.id) }}" data-tfk-confirm="Really remove {{ member.name }}?" class="dropdown-item"><i class="bi bi-trash text-danger me-2"></i>Remove</a></li>
              {% endif %}
            </ulv>
          </div>
          {% endfor %}
        {% endfor %}
        {% if project.isadmin %}
          <div><button type="button" class="btn btn-action p-0" data-bs-toggle="modal" data-bs-target="#usersModal" data-member-ids="{{ project.mids }}" data-project-id="{{ project.id }}"><i class="bi bi-plus-circle-dotted"></i></button></div>
        {% endif %}
        </div>
      </div>
    </{% if project.isadmin %}form{% else %}div{% endif %}>
  </div>
  {% endfor %}
</div>
<h5 class="text-primary px-2 fw-normal mt-5 mb-2 py-2 border-bottom">My archived projects</h5>
{% for item in archived %}
<div class="px-2 my-1 d-flex">
  <div class="pe-2"><i class="bi bi-archive"></i></div>
  <div><a href="{{ url_for('projects.project_view', id=item.id) }}" class="text-decoration-none link-dark">{{ item.title }}</a></div>
</div>
  {% endfor %}

{% endblock %}

application/templates/projects_view.html
{% extends "layout/projects.html" %}

{% block content %}
<h2 class="page-title">
    {% if data.isadmin %}
    <a href="#!" class="btn btn-action btn-project-edit pt-2 pe-0 float-end" data-id="{{ project.id }}"><i class="bi bi-pencil-fill"></i></a>
    {% endif %}
    <a href="{{ url_for('projects.project_list') }}" class="text-decoration-none text-secondary">Projects</a>
    &rsaquo; {{ project.title }}
</h2>

{% if not status %}
<div class="alert alert-warning py-2" role="alert">
    Project is archived.
    {% if data.isadmin %}
    <button class="btn btn-link float-end py-0"data-tfk-confirm="Do you want to reactivate this project?" data-tfk-action="{{ url_for('projects.api_project_open', pid=project.id) }}">Re-open?</button>
    {% endif %}
</div>
{% endif %}

<div class="row bg-white px-lg-1 py-lg-3 mx-lg-1 rounded">
    <div class="col-12 col-sm-6 col-md-8">
        <div class="text-uppercase text-muted small">Description</div>
        <p>{{ project.description | safe }}</p>
        <div class="text-uppercase text-muted small mt-4">Members</div>
        <div class="project-users mt-2">
        {% for ridx, rlabel in [('r2','admin'),('r1','member'),('r0','observer')] %}
          {% for member in data.get(ridx) %}
          <div data-userid="{{ member.id }}" class="btn-user btn-user-{{ rlabel }} dropdown-center order-2 order-md-5">
            {% set rn = ridx[1] | int %}
            <a href="#!" class="dropdown-toggle arrow-none text-muted" data-bs-toggle="dropdown" aria-expanded="false">{{ member.avatar(rlabel | title) | safe }}</a>
            <ul class="dropdown-menu">
              <li><h6 class="dropdown-header">{{ member.name }} ({{ rlabel | title}})</h6></li>
              <li><a href="javascript:void(0);" class="dropdown-item"><i class="bi bi-person-square me-2"></i>View profile</a></li>
              {% if data.isadmin and member.id != current_user.id %}
              {% if rn < 2 %}
              <li><a href="{{ url_for('projects.api_project_members_promote', pid=project.id, uid=member.id) }}" data-tfk-ajax="post" class="dropdown-item"><i class="bi bi-caret-up-square text-success me-2"></i>Promote member</a></li>
              {% endif %}
              {% if rn > 0 %}
              <li><a href="{{ url_for('projects.api_project_members_demote', pid=project.id, uid=member.id) }}" data-tfk-ajax="post" class="dropdown-item"><i class="bi bi-caret-down-square text-warning me-2"></i>Demote member</a></li>
              {% endif %}
              <li><a href="{{ url_for('projects.api_project_members_remove', pid=project.id, uid=member.id) }}" data-tfk-confirm="Really remove {{ member.name }}?" class="dropdown-item"><i class="bi bi-trash text-danger me-2"></i>Remove</a></li>
              {% endif %}
            </ulv>
          </div>
          {% endfor %}
        {% endfor %}
        {% if data.isadmin %}
          <div><button type="button" class="btn btn-action p-0" data-bs-toggle="modal" data-bs-target="#usersModal" data-member-ids="{{ data.mids }}"  data-project-id="{{ data.id }}"><i class="bi bi-plus-circle-dotted"></i></button></div>
        {% endif %}
        </div>
        {% if data.isadmin and data.status > 0 %}
        <div class="text-end"><button type="button" class="action-archive-project btn btn-link btn-sm text-danger" data-tfk-confirm="Do you want to archive this project?" data-tfk-action="{{ url_for('projects.api_project_archive', pid=project.id) }}"><i
          class="bi bi-archive pe-1"></i>Archive project</button></div>
        {% endif %}
        <hr class="d-sm-none" />
    </div>
    <div class="col-6 col-sm-3 col-md-2 border-sm-start">
        <div class="mb-2 pb-2 border-bottom">
            <div class="text-uppercase text-muted small">Start</div>
            <div class="fw-semibold">{{ project.start or '-' }}</div>
        </div>
        <div class="mb-2 pb-2 border-bottom">
            <div class="text-uppercase text-muted small">Time Est.</div>
            <div class="fw-semibold">-</div>
        </div>
        <div class="mb-2">
            <div class="text-uppercase text-muted small">Budget</div>
            <div class="fw-semibold">{{ project.budget }}</div>
        </div>
    </div>
    <div class="col-6 col-sm-3 col-md-2 border-start">
        <div class="mb-2 pb-2 border-bottom">
            <div class="text-uppercase text-muted small">Deadline</div>
            <div class="fw-semibold">{{ project.deadline or '-' }}</div>
        </div>
        <div class="mb-2 pb-2 border-bottom">
            <div class="text-uppercase text-muted small">Time Spent</div>
            <div class="fw-semibold">-</div>
        </div>
        <div class="mb-2">
            <div class="text-uppercase text-muted small">Status</div>
            <div class="fw-semibold">{{ project.status }}</div>
        </div>
    </div>
</div>
<hr class="d-lg-none" />
<div class="project-task-list bg-white px-lg-1 py-lg-3 mt-lg-4 mx-lg-1 rounded">
    Task list...
</div>
</div>
{% endblock %}

application/templates/settings_account.html
{% extends "layout/settings.html" %}

{% block content %}

    <h2 class="page-title">My Account</h2>
    <form id="account-form" action="{{ url_for('settings.api_user_save') }}" method="POST" style="max-width:600px">
        <input type="hidden" name="id" value="{{ data.id }}" />
        <div class="row mb-3">
            <div class="col-12 col-sm-9 offset-sm-3 d-flex align-items-end"> 
                <div id="user-avatar" class="btn-user btn-user-lg pe-3">{{ data.avatar() | safe }}</div>
                <div class="small pb-2">
                    <table>
                        <tr>
                            <td class="pe-3 text-muted">Created on:</td>
                            <td>{{ data.creation | user_time }}</td>
                        </tr>
                        <tr>
                            <td class="pe-3 text-muted">Last update:</td>
                            <td>{{ data.update | user_time }}</td>
                        </tr>
                        <tr>
                            <td class="pe-3 text-muted">Last login:</td>
                            <td>{{ data.lastlogin | user_time }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            <label for="iThumb" class="col-sm-3 col-form-label">Profile image</label>
            <div class="col-sm-9">
                <input type="text" name="thumbnail" class="form-control" id="iThumb" value="{{ data.thumbnail or '' }}" />
            </div>
        </div>
        <div class="row mb-3">
            <label for="iName" class="col-sm-3 col-form-label">Name</label>
            <div class="col-sm-9">
                <input type="text" name="name" class="form-control" id="iName" value="{{ data.name }}" />
            </div>
        </div>
        <div class="row mb-3">
            <label for="iEmail" class="col-sm-3 col-form-label">Email</label>
            <div class="col-sm-9">
                <div class="p-2">{{ data.email }}</div>
            </div>
        </div>
        <div class="row mb-3">
            <label for="ipwd" class="col-sm-3 col-form-label">Password</label>
            <div class="col-sm-9">
                <input type="password" name="password" class="form-control" id="iPwd" autocomplete="new-password" />
                <div class="small text-muted">Enter password only if you want to update it</div>
            </div>
        </div>
        <div class="row mb-3">
            <label for="iTz" class="col-sm-3 col-form-label">Timezone</label>
            <div class="col-sm-9">
                <select id="iTz" name="timezone" class="form-select">
                {% for tzg in timezones %}
                {% if timezones[tzg]|length > 1 %}
                <optgroup label="{{ tzg }}">
                    {% for tz in timezones[tzg] %}
                    <option value="{{ tzg }}/{{ tz }}"{% if tzg+"/"+tz == current_user.timezone %} selected{% endif %}>{{ tz }}</option>
                    {% endfor %}
                </optgroup>
                {% else %}
                <option value="{{ tzg }}">{{ tzg }}</option>
                {% endif %}
                {% endfor %}
                </select>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-12 col-sm-9 offset-sm-3">
                <button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Save</button>
            </div>
        </div>

    </form>

{% endblock %}