application/views/projects.py
from sqlalchemy import desc

from flask import Blueprint, render_template, jsonify, redirect, request, url_for, flash, g
from flask_login import login_required, current_user

from application import app
from application.models import *
from application.utils import utils

projects = Blueprint('projects', __name__)

@projects.before_request
@login_required
def login_required_for_all_request():    
    pass  

@projects.route("/projects")
def project_list():
    # List of projects, invitations, join and leave projects
    projects = utils.load_projects(current_user)
    # list archived projects
    pqry = ProjectModel.query
    if current_user.role < 4:
        pqry = pqry.join(ProjectUserModel) \
            .filter(ProjectModel.status == 0, ProjectUserModel.user_id == current_user.id)
    else:
        pqry = pqry.filter(ProjectModel.status == 0)
    archlist = utils.parse_projects(pqry.order_by(ProjectModel.title).all(), current_user.id)
    # list users
    users = UserModel.query.filter(UserModel.role > 0).order_by(UserModel.name).all()
    # prepare view
    g.jscript.append(url_for('static', filename='js/dragula.min.js'))
    g.jscript.append(url_for('static', filename='js/projects.js'))
    return render_template("projects.html",
        title="Pacific Data Hub",
        projects=projects,
        archived=archlist,
        users=users,
        menu="projects_list"
    )

@projects.route("/projects/<int:id>")
def project_view(id):
    project = ProjectModel.query.filter_by(id=id).first()
    if not project:
        flash('Project not found', 'error')
        return redirect(url_for('projects.project_list'))
    asso = ProjectUserModel.query.filter_by(project_id=id, user_id=current_user.id).first()
    if not asso:
        flash('Access denied', 'error')
        return redirect(url_for('projects.project_list'))
    # list users
    users = UserModel.query.filter(UserModel.role > 0).order_by(UserModel.name).all()
    # prepare view
    g.jscript.append(url_for('static', filename='js/projects.js'))
    return render_template("projects_view.html",
        title="Pacific Data Hub",
        data = utils.parse_project(project, current_user.id),
        project = project.get_html(),
        status = project.status,
        users=users,
        menu="projects_list"
    )

@projects.route("/api/project/load/<id>")
@projects.route("/api/project/load/<id>/<mode>")
def api_project_load(id, mode="data"):
    if current_user.role < 1:
        return jsonify({'error': 'Action not allowed'})
    item = ProjectModel.query.filter_by(id=id).first()
    if not item:
        return jsonify({'error': 'Project does not exist'})
    if mode == 'data':
        return jsonify(item.get_dict())
    else:
        return jsonify(item.get_html())


@projects.route("/api/project/save", methods=['POST'])
def api_project_save():
    pid = int(request.form['id']) if request.form.get('id') else False
    # init project
    item = ProjectModel()
    if pid:
        item = ProjectModel.query.filter_by(id=pid).first()
        if not item:
            return jsonify({'error': 'Project does not exist'})
        err = utils.wrong_project_permission(pid, current_user.id, 2)
        if err:
            return jsonify(err)
    # set properties
    item.title = request.form.get('title','').strip()
    item.description = request.form.get('description','')
    item.setDate('start',request.form.get('start') or None)
    item.setDate('deadline', request.form.get('deadline') or None)
    item.budget = request.form.get('budget') or None # TODO check float
    item.status = request.form.get('status', 0)
    # check
    is_valid = item.is_valid()
    if is_valid != True:
        return jsonify({'error': list(is_valid.values())})
    # add default user to new projects
    if not pid:
        asso = ProjectUserModel()
        asso.member = current_user
        asso.project = item
        asso.role = 2 # admin
        db.session.add(asso)
    # save in DB
    db.session.commit()
    # report to user
    msg = "Project {}".format('Updated' if pid else 'Created')
    flash(msg, 'success')
    return jsonify({
        'success': msg,
        'pid': item.id
    })

@projects.route("/api/project/lists/save", methods=['POST'])
def api_project_lists_save():
    pid = request.form.get('pid')
    err = utils.wrong_project_permission(pid, current_user.id, 1)
    if err:
        return jsonify(err)
    # Load projct
    proj = ProjectModel.query.get(pid)
    # Create list item
    if (request.form.get('newitem')):
        item = ListModel(
            project_id = pid,
            title=request.form['newitem'],
            position = proj.get_next_list_position(),
            status = 1
        )
        db.session.add(item)
        db.session.commit()
        return jsonify({
            'success': "New list created",
            'pid': pid,
            'lid': item.id,
            'position': item.position
        })
    else:
        # save list items
        items = request.form.to_dict()
        pos = 0
        for idx in items:
            if 'item_' in idx:
                lid = int(idx[5:])
                item = ListModel.query.get(lid)
                if items[idx]:
                    # -TODO- delete lists with empty names?
                    item.title = items[idx]
                item.project_id = pid
                item.position = pos
                pos = pos+1
        db.session.commit()
        msg = 'List item saved!'
        return jsonify({
            'success': msg,
            'noreload': True,
            'pid': pid
        })

@projects.route("/api/project/lists/del/<int:id>", methods=['GET','POST'])
def api_project_lists_del(id):
    # 1. load list
    item = ListModel.query.get(id)
    # 2. Check admin rights
    err = utils.wrong_project_permission(item.project_id, current_user.id, 2)
    if err:
        return jsonify(err)
    # 3. load tasks and check list is empty
    # -TODO-
    # 4. delete list
    db.session.delete(item)
    db.session.commit()
    # 5. frontend feedback
    if request.form.get('frontend', False):
        flash('List deleted!')
    return jsonify({
        'success': 'List deleted!'
    })

@projects.route("/api/project/members/save", methods=['POST'])
def api_project_members_save():
    pid = request.form.get('pid')
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    # load current members
    assos = ProjectUserModel.query.filter_by(project_id=pid).all()
    members = []
    for itm in assos:
        members.append(itm.user_id)
    # add new members
    tot = 0
    for mid in request.form.get('usersel'):
        if mid not in members:
            asso = ProjectUserModel()
            asso.user_id = mid
            asso.project_id = pid
            asso.role = 0 # guest
            db.session.add(asso)
            tot = tot+1
    if tot:
        db.session.commit()
    # report
    msg = f"{tot} members added to project"
    flash(msg, 'success')
    return jsonify({
        'success': msg,
        'pid': pid
    })

@projects.route("/api/project/members/promote/<int:pid>/<int:uid>", methods=['GET','POST'])
def api_project_members_promote(pid, uid):
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    asso = ProjectUserModel.query.filter_by(project_id=pid, user_id=uid).first()
    if asso.role < 2:
        asso.role = asso.role + 1
        db.session.commit()
        msg = "User successfully promoted"
        flash(msg, 'success')
        return jsonify({
            'success': msg,
            'pid': pid
        })
    else:
        return jsonify({
            'error': 'Member is already an admin'
        })

@projects.route("/api/project/members/demote/<int:pid>/<int:uid>", methods=['GET','POST'])
def api_project_members_demote(pid, uid):
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    asso = ProjectUserModel.query.filter_by(project_id=pid, user_id=uid).first()
    if asso.role > 0:
        asso.role = asso.role - 1
        db.session.commit()
        msg = "Member successfully demoted"
        flash(msg, 'success')
        return jsonify({
            'success': msg,
            'pid': pid
        })
    else:
        return jsonify({
            'error': 'Member is already a guest'
        })

@projects.route("/api/project/members/remove/<int:pid>/<int:uid>", methods=['GET','POST'])
def api_project_members_remove(pid, uid):
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    asso = ProjectUserModel.query.filter_by(project_id=pid, user_id=uid).first()
    db.session.delete(asso)
    db.session.commit()
    # report
    msg = "User successfully removed from project members"
    flash(msg, 'success')
    return jsonify({
        'success': msg,
        'pid': pid
    })
    
@projects.route("/api/project/archive/<int:pid>", methods=['GET','POST'])
def api_project_archive(pid):
    # Load project and check permissions
    item = ProjectModel.query.filter_by(id=pid).first()
    if not item:
        return jsonify({'error': 'Project does not exist'})
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)
    # update status (0 = closed)
    item.status = 0
    # save in DB
    db.session.commit()
    # report
    msg = "Project has been archived"
    flash(msg, 'success')
    return jsonify({
        'success': msg,
        'pid': pid
    })

@projects.route("/api/project/open/<int:pid>", methods=['GET','POST'])
def api_project_open(pid):
    # Load project and check permissions
    item = ProjectModel.query.filter_by(id=pid).first()
    if not item:
        return jsonify({'error': 'Project does not exist'})
    err = utils.wrong_project_permission(pid, current_user.id, 2)
    if err:
        return jsonify(err)

application/views/settings.py
from sqlalchemy import desc

from flask import Blueprint, render_template, jsonify, request, url_for, flash, g
from flask_login import login_required, current_user

from application import app
from application.models import *
from application.utils import utils

settings = Blueprint('settings', __name__)

@settings.before_request
@login_required
def login_required_for_all_request():    
    pass

@settings.route("/settings/account")
def account():
	# User account settings, i.e. name, email, password, avatar
	# item = UserModel.query.get(current_uset)
	g.jscript.append(url_for('static', filename='js/settings_account.js'))
	return render_template("settings_account.html",
		title="Pacific Data Hub",
		menu="settings_account",
		data=current_user,
		timezones=utils.get_timezones()
	)

@settings.route("/settings/preferences")
def preferences():
	# User preferences, i.e. timezone, default view, notifications, outlook sync
	opts = {
		'default_views': app.config['TASK_VIEWS']
	}
	g.jscript.append(url_for('static', filename='js/settings_preferences.js'))
	return render_template("settings_preferences.html",
		title="Pacific Data Hub",
		menu="settings_preferences",
		data=current_user.get_preferences(),
		options = opts
	)

@settings.route("/api/preferences/save", methods=['POST'])
def api_preferences_save():
	uid = int(request.form['id']) if request.form.get('id') else current_user.id
	if uid != current_user.id and current_user.role < 3:
		return jsonify({'error': 'You must be admin to edit users'})
	item = UserModel.query.filter_by(id=uid).first()
	if not item:
		return jsonify({'error': 'User does not exist'})
	item.set_preference('default_view', request.form.get('default_view', 'list'))
	item.set_preference('notif_instant', request.form.get('notif_instant', False))
	item.set_preference('notif_daily', request.form.get('notif_daily', False))
	db.session.commit()
	msg = "User preferences saved"
	return jsonify({'success': msg})

@settings.route("/settings/users")
def users():
	# User management
	qry = UserModel.query
	if (current_user.role < 4):
		qry = qry.filter(UserModel.role > 0)
	items = qry.order_by(desc(UserModel.role), UserModel.name).all()
	g.jscript.append(url_for('static', filename='js/settings_users.js'))
	return render_template("settings_users.html",
		title="Pacific Data Hub",
		menu="settings_users",
		data=items,
		roles=app.config['USER_ROLES'],
		timezones=utils.get_timezones()
	)

@settings.route("/api/users/load/<id>")
def api_user_load(id):
	if current_user.role < 2:
		return jsonify({'error': 'Action not allowed'})
	item = UserModel.query.filter_by(id=id).first()
	if not item:
		return jsonify({'error': 'User does not exist'}) 
	if current_user.role <= item.role:
		return jsonify({'error': 'Action not allowed'})
	if not item.timezone:
		item.timezone = 'UTC'
	return jsonify(item.get_dict())

@settings.route("/api/users/save", methods=['POST'])
def api_user_save():
	uid = int(request.form['id']) if request.form.get('id') else False
	uro = int(request.form['role']) if request.form.get('role') else 0
	if (uid != current_user.id and uro > current_user.role):
		# trying to raise user to a higher level than ourself
		return jsonify({'error': 'Action not allowed'})
	# set user
	item = UserModel()
	if uid:
		item = UserModel.query.filter_by(id=uid).first()
		if not item:
			return jsonify({'error': 'User does not exist'})
		elif uid != current_user.id:
			if current_user.role < 3:
				return jsonify({'error': 'You must be admin to edit users'})
			if current_user.role <= item.role:
				return jsonify({'error': 'Can not edit user with a higher role'})
	elif current_user.role < 3:
		return jsonify({'error': 'You must be admin to create users'})
		
	item.name = request.form.get('name','').strip()
	item.timezone = request.form.get('timezone','UTC')
	if not uid or (uid != current_user.id and current_user.role > 3):
		# set email only for new users
		# only super admin can change email (for now)
		item.email = request.form.get('email','').strip()
	if (uid and uid == current_user.id):
		# user is updating itself
		item.thumbnail = request.form.get('thumbnail', '')
	else:
		# admin is updating another user
		item.role = uro
	# check if password is getting updated
	pwd = request.form.get('password','').strip()
	if (pwd):
		# set password only when creating or updating it
		# -TODO- check if the password is secure enough (within set_password method)
		item.set_password(pwd)
	if not item.is_valid():
		return jsonify({'error': 'Missing or invalid fields'})
	if not uid:
		db.session.add(item)
	db.session.commit()
	msg = "User {}".format('Updated' if uid else 'Created')
	flash(msg, 'success')
	return jsonify({
		'success': msg, 
		'avatar': item.avatar()
	})


@settings.route("/api/users/delete/<int:id>", methods=['POST'])
def api_user_delete(id):
	# id = int(request.form['id']) if request.form.get('id') else False
	if not id:
		return jsonify({'error': 'User not specified'})
	if current_user.role < 3:
		return jsonify({'error': 'Insufficient permissions #2'})
	item = UserModel.query.get(id)
	if item:
		# delete if no task, no comment, nothing
		# db.session.delete(item)
		# else disable it
		item.role = 0
		db.session.commit()
		flash('User account has been disabled', 'success')
		return jsonify({'success': 'User disabled'})
	else: 
		return jsonify({'error': 'User does not exist'})
    # return redirect(url_for('adminUser'))

application/views/user.py
from sqlalchemy import desc

from flask import Blueprint, render_template, jsonify, url_for, flash, redirect, request as flask_request
from flask_login import LoginManager, current_user, login_user, logout_user, login_required

from application import app
from application.models import *
from application.utils import utils

user = Blueprint('user', __name__)


@user.route('/user/login', methods = ['POST', 'GET'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('index'))

	next_url = flask_request.args.get('next', flask_request.form.get('next', ''))
     
	if flask_request.method == 'POST':
		email = flask_request.form['email']
		user = UserModel.query.filter_by(email = email).first()
		if user is not None and user.check_password(flask_request.form['password']):
			if (not user.role):
				flash('Your account is disabled', 'error')
			else:
				utils.set_last_login(user.id)
				login_user(user)
				flash('You are now logged in')
				if (next_url):
					return redirect(next_url)
				else:
					return redirect(url_for('index'))
		else:
			flash('Wrong email address or password', 'error')
     
	return render_template('user/login.html',
		title='Login',
		menu='login',
		next=next_url)

@user.route('/user/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
     
    if flask_request.method == 'POST':
        email = flask_request.form['email']
        username = flask_request.form['name']
        password = flask_request.form['password']
 
        if UserModel.query.filter_by(email=email).first():
            return ('Email already Present')
	
		# -TODO- register with role = 0 and send confirmation email to move to 1
        user = UserModel(email=email, name=username, role=1)
        user.set_password(password)
        user.check_gravatar(True)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.login'))

    return render_template('user/register.html',
		title='Register',
		menu='register')

@user.route('/logout')
def logout():
	logout_user()
	flash('You are now logged out')
	return redirect(url_for('index'))

application/templates/layout/page.html
<!DOCTYPE html>
<html>
<head>
  <title>TaskFreak</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% for item in g.css %}
  <link rel="stylesheet" type="text/css" href="{{ item }}">
  {% endfor %}
  <link rel="stylesheet" type="text/css" href="/static/css/app.css">
</head>
<body>
  
<nav class="navbar navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">{{ title }}</a>
    {% block headerform %}
    {% endblock %}
    <div class="d-flex">
    {% block navbuttons %}

    {% if current_user.is_authenticated %}
      <a href="#!" class="hamburger d-block d-lg-none">
        <span class="line line1"></span>
        <span class="line line2"></span>
        <span class="line line3"></span>
      </a>
      <div class="dropdown">
        <a class="btn-nav btn-user dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          {{ current_user.avatar() | safe }}
        </a>
        <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end">
          <li><a class="dropdown-item" href="{{ url_for('projects.project_list') }}"><i class="bi bi-briefcase-fill me-2"></i>Projects &amp; Lists</a></li>
          <li><a class="dropdown-item" href="{{ url_for('settings.preferences') }}"><i class="bi bi-house-heart-fill me-2"></i>Preferences</a></li>
          <li><a class="dropdown-item" href="{{ url_for('settings.account') }}"><i class="bi bi-person-lines-fill me-2"></i>Account</a></li>
          {% if current_user.role > 2 %}
          <li><a class="dropdown-item" href="{{ url_for('settings.users') }}"><i class="bi bi-people-fill me-2"></i>Users</a></li>
          {% endif %}
          <li><a class="dropdown-item" href="{{ url_for('user.logout') }}"><i class="bi bi-box-arrow-right me-2"></i>Logout</a></li>
        </ul>
      </div>
    {% endif %}

    {% endblock %}
    </div>
  </div>
</nav>

<div class="wrapper">

  {% block sidebar %}
  {% endblock %}

  <section class="main container-fluid page-{{ menu }}">

    {% block content %}
    {% endblock %}

  </section>
  
</div>

{% block modals %}

{% endblock %}

<div class="modal" id="confirmModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
      <form action="#!" method="post" class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="confirmModalLabel">Are you sure?</h5>
              <input type="hidden" name="frontend" value="true" />
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              ...
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Yes, confirm</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No, cancel</button>  
          </div>
      </form>
  </div>
</div>

<div class="toast-container position-fixed bottom-0 end-0 p-3">

  <div id="live-toast" class="toast align-items-center border-0" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
      <div class="toast-body"></div>
      <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>

  {% with messages = get_flashed_messages(True) %}
      {% if messages %}
          {% for cat, message in messages %}
          <div class="toast flash align-items-center {{ cat | toast_class }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
              <div class="toast-body">
                {{ message }}
              </div>
              <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
          </div>
          {% endfor %}
          </ul>
      {% endif %}
  {% endwith %}

</div>

{% for item in g.jscript %}
<script type="text/javascript" src="{{ item }}"></script>
{% endfor %}
</body>
</html>

application/templates/layout/projects.html
{% extends "layout/settings.html" %}

{% block modals %}

<div class="modal fade" id="editModal" tabindex="-1" data-bs-backdrop="static" aria-labelledby="editProjectLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg modal-fullscreen-lg-down modal-dialog-scrollable">
    <form id="project-form" action="{{ url_for('projects.api_project_save') }}" method="post" class="modal-content" autocomplete="off">
      <input id="iId" type="hidden" name="id" value="0" />
      <div class="modal-header modal-smaller bg-light">
        <h5 class="modal-title" id="editTaskLabel">Edit Project</h5>
        <div class="float-end">
          <button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Save</button>
          <button type="button" class="btn btn-my-close ps-1" data-bs-dismiss="modal"
            aria-label="Close">&times;</button>
        </div>
      </div>
      <div class="modal-body">
        <div class="mb-3">
          <input id="iTitle" type="text" class="form-control" name="title" value="" placeholder="Title" />
        </div>
        <div class="row">
          <div class="col-12 col-lg-9">
            <div class="mb-3">
              <textarea id="iDescription" name="description" class="form-control" value="" placeholder="Description"
                rows="13"></textarea>
            </div>
          </div>
          <div class="col-12 col-lg-3">
            <div class="mb-3">
              <label for="iStart" class="form-label mb-1 text-muted">Start</label>
              <div class="input-group date datepicker">
                <input id="iStart" name="start" type="text" class="form-control" />
                <span class="input-group-append">
                  <span class="input-group-text bg-light d-block">
                    <i class="bi bi-calendar-date"></i>
                  </span>
                </span>
              </div>
            </div>
            <div class="mb-3">
              <label for="iDeadline" class="form-label mb-1 text-muted">Deadline</label>
              <div class="input-group date datepicker">
                <input id="iDeadline" name="deadline" type="text" class="form-control" />
                <span class="input-group-append">
                  <span class="input-group-text bg-light d-block">
                    <i class="bi bi-calendar-date"></i>
                  </span>
                </span>
              </div>
            </div>
            <div class="mb-3">
              <label for="iBudget" class="form-label mb-1 text-muted">Budget</label>
              <input id="iBudget" type="text" class="form-control" name="budget" value="" />
            </div>
            <div class="mb-3">
              <label for="iStatus" class="form-label mb-1 text-muted">Status</label>
              <select id="iStatus" name="status" class="form-select" aria-label="Default select example">
                <option value="0">Closed</option>
                <option value="1" selected>Open (private)</option>
                <option value="2">Open (public)</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="modal fade" id="usersModal" tabindex="-1" aria-labelledby="usersLabel" aria-hidden="true">
  <div class="modal-dialog modal-md modal-fullscreen-md-down mt-md-5 pt-md-2">
    <form action="{{ url_for('projects.api_project_members_save') }}" method="post" class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add new members</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="pid" value="" />
        <div class="row users-grid">
          {% for usr in users %}
          <div class="col btn-user" id="usrsel-{{ usr.id }}">
            <input type="checkbox" class="d-none" id="chk-sel-{{ usr.id }}" name="usersel" value="{{ usr.id }}" />
            <label for="chk-sel-{{ usr.id }}">{{ usr.avatar() | safe }}<small>{{ usr.name }}</small></label>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Add selected users</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

application/templates/layout/settings.html
{% extends "layout/page.html" %}

{% block sidebar %}

<nav class="sidebar">
  <h4>Settings</h4>
  <ul>
    <li><a href="{{ url_for('projects.project_list') }}" class="{% if menu=='projects_list' %}active{% endif %}"><i class="bi bi-briefcase-fill me-2"></i>Projects &amp; Lists</a></li>
    <li><a href="{{ url_for('settings.preferences') }}" class="{% if menu=='settings_preferences' %}active{% endif %}"><i class="bi bi-house-heart-fill me-2"></i>Preferences</a></li>
    <li><a href="{{ url_for('settings.account') }}" class="{% if menu=='settings_account' %}active{% endif %}"><i class="bi bi-person-lines-fill me-2"></i>Account</a></li>
  </ul>
  <h4>Management</h4>
  <ul>
    <li><a href="{{ url_for('settings.users') }}" class="{% if menu=='settings_users' %}active{% endif %}"><i class="bi bi-people-fill me-2"></i>Users</a></li>
  </ul>
</nav>

{% endblock %}